# .github/workflows/claude.yml
name: Claude Code Generator

on:
  issues:
    types: [opened]

jobs:
  claude-generate:
    runs-on: ubuntu-latest
    environment: testdev

    permissions:
      contents: read
      pull-requests: read
      issues: write
      id-token: write
      actions: write

    outputs:
      claude_response: ${{ steps.claude-generate-code.outputs.response }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code Generation
        id: claude-generate-code
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}

      - name: Extract Claude's Generated Code
        id: extract-code
        if: always() && steps.claude-generate-code.outputs.response != ''
        run: |
          RAW_RESPONSE="${{ steps.claude-generate-code.outputs.response }}"
          echo "Raw Claude Response:"
          echo "$RAW_RESPONSE"

          GENERATED_CODE=$(echo "$RAW_RESPONSE" | sed -n '/```/,/```/p' | grep -v '```')

          if [ -z "$GENERATED_CODE" ]; then
            echo "::warning::No code block found in Claude's response. Exiting without creating PR."
            echo "has_code=false" >> $GITHUB_OUTPUT
          else
            echo "::notice::Code block successfully extracted."
            echo "$GENERATED_CODE" > generated_code.txt
            echo "has_code=true" >> $GITHUB_OUTPUT
          fi

      - name: Dispatch PR Creation Workflow
        if: steps.extract-code.outputs.has_code == 'true'
        uses: actions/github-script@v7
        id: dispatch-pr-creation
        with:
          script: |
            const fs = require('fs');
            const generatedCode = fs.readFileSync('generated_code.txt', 'utf8');

            const pr_number = context.payload.issue.number;
            const issue_or_pr_id = `#${pr_number}`;
            const originalPrAuthor = context.payload.issue.user.login;

            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'claude-create-pr.yml',
              ref: context.ref,
              inputs: {
                pr_title: `feat(ai): Auto-generated changes for ${issue_or_pr_id}`,
                pr_body: `🤖 This Pull Request contains auto-generated code by Claude AI based on the prompt/issue ${issue_or_pr_id}.\n\n---Generated Code---\n\`\`\`\n${generatedCode}\n\`\`\`\n\n---Claude's Full Response---\n${process.env.RAW_CLAUDE_RESPONSE}`,
                generated_code: generatedCode,
                source_issue_or_pr: pr_number.toString(),
                source_event_type: context.eventName,
                original_pr_author: originalPrAuthor
              }
            });
            console.log('Dispatched claude-create-pr.yml workflow.');
        env:
          RAW_CLAUDE_RESPONSE: ${{ steps.claude-generate-code.outputs.response }}